/*
 * generated by Xtext 2.10.0
 */
package swi.dod.nxp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
