/**
 * generated by Xtext 2.10.0
 */
package swi.dod.nxp.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link swi.dod.nxp.dsl.Model#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see swi.dod.nxp.dsl.DslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Commands</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' attribute list.
   * @see swi.dod.nxp.dsl.DslPackage#getModel_Commands()
   * @model unique="false"
   * @generated
   */
  EList<String> getCommands();

} // Model
