/*
 * generated by Xtext 2.10.0
 */
package swi.dod.nxp.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import swi.dod.nxp.ui.internal.NxpActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return NxpActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return NxpActivator.getInstance().getInjector(NxpActivator.SWI_DOD_NXP_DSL);
	}
	
}
